### ISSUE TITLE
Plural support

### ISSUE THREAD

**Issue by timothyarmes** [vazco/meteor-universe-i18n#9]
Can you please add support for selecting the correct plural translation based on a count value?

**Comment by cristo-rabani** [comment]
Hello, 
We consider adding such functionality but we must devise api.
So, maybe we try use some library for it.

**Comment by bompi88** [comment]
Maybe consider following these language [rules](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html)? `react-intl` utilises those rules if I understand perfectly. The package could look for `key + '_few'`, `key + '_many'` and `key + '_other'` based on a count value. There should be a way to configure the limits of `few` and `many`? I have problems comprehending what's the difference between `many` and `other`, but maybe some of you know the difference? 

```yaml
message: You have one message in your inbox
message_few: You have a few messages in your inbox
message_many: You have a bunch of messages in your inbox
message_other: You have messages in your inbox
```
